### ISSUE TITLE
Please, never do this!

### ISSUE THREAD

**Issue by zerezhka** [nurjan84/weather_sample_app#1]
https://github.com/nurjan84/weather-app-MVP/blob/e7f7cb48108bac893ced654e36b08a66816d0f04/app/src/main/java/kz/nta/kazweather/adapters/WeatherListAdapter.kt#L21

![kendrick](https://user-images.githubusercontent.com/10316435/52709025-cf98e280-2fb5-11e9-8c2c-ef9198b88d1e.jpg)

**Comment by nurjan84** [comment]
ok

**Comment by zerezhka** [comment]
[ref](https://www.youtube.com/watch?v=GF8aaTu2kg0)
